// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf65Y2u80qxkM1hWrw5zPPLpey-6tZQ_0',
    appId: '1:31047436964:android:9510b5c3f4df32c6323431',
    messagingSenderId: '31047436964',
    projectId: 'fayez-6eab2',
    storageBucket: 'fayez-6eab2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMgRKAYziecqKLrxYU8PznlNM8ZrSqTjg',
    appId: '1:31047436964:ios:e5beab1673039352323431',
    messagingSenderId: '31047436964',
    projectId: 'fayez-6eab2',
    storageBucket: 'fayez-6eab2.firebasestorage.app',
    androidClientId: '31047436964-1sad8m7th9f91sthc7vp8avfs44f3ctm.apps.googleusercontent.com',
    iosClientId: '31047436964-qdua7td8jrh9r1lp91ac7or0u342pegn.apps.googleusercontent.com',
    iosBundleId: 'com.bluewhale.whatsorder',
  );
}
